eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9100/eureka/
server:
  port: 8008
spring:
  application:
    name: byyeungc-zuul

zuul:
  routes:
    api-test:
         path: /api-test/**
         serviceId: byyeungc-test
         
management:
   endpoints:
      web:
         exposure:
            include: "*"
ribbon: 
   eureka: 
   enabled: true